import Config

# Configure your database
config :mce, Mce.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  port: "5433",
  database: "mce_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :mce, MceWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "VV4h85PLqwx5zgOto1xwgujeKtD3fvpfw+6njkREBYFcSfJMefvVTSNED/AxMpwu",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:mce, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:mce, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :mce, MceWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/mce_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :mce, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Mailer configuration for development
# Set USE_RESEND=true in .env to test with Resend instead of local mailbox
if System.get_env("USE_RESEND") == "true" do
  config :swoosh, :api_client, Swoosh.ApiClient.Req

  resend_api_key =
    System.get_env("RESEND_API_KEY") ||
      raise "RESEND_API_KEY is required when USE_RESEND=true"

  mail_from_name =
    System.get_env("MAIL_FROM_NAME") ||
      raise "MAIL_FROM_NAME is required when USE_RESEND=true"

  mail_from_email =
    System.get_env("MAIL_FROM_EMAIL") ||
      raise "MAIL_FROM_EMAIL is required when USE_RESEND=true"

  config :mce, Mce.Mailer,
    adapter: Swoosh.Adapters.Resend,
    api_key: resend_api_key,
    from_name: mail_from_name,
    from_email: mail_from_email
else
  # Default: use local adapter, emails visible at /dev/mailbox
  config :swoosh, :api_client, false
end
